# Generated by Django 5.2.1 on 2025-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('categoria_estrellas', models.PositiveSmallIntegerField()),
                ('descripcion_general', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
