# Generated by Django 5.2.1 on 2025-05-22 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('numero_adultos', models.PositiveIntegerField()),
                ('numero_ninos', models.PositiveIntegerField(default=0)),
                ('estado_reserva', models.CharField(default='Pendiente', max_length=20)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empleado_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_reservas', to='empleados.empleado')),
                ('empleado_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_reservas', to='empleados.empleado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
            ],
        ),
    ]
